//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayitId { get; set; }
        public string kayitKulId { get; set; }
        public string kayitDosyaId { get; set; }
    
        public virtual Dosya Dosya { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
